using UnityEngine;
using System.Collections;

public class CubeMapperUtil : MonoBehaviour {
	/*
	 * Attach to gameobject to set cubemap generated by cubemapper object
	 * 
	 * Scans each material for keywords and sets the cubemap accordingly
	 * 
	 */
	
	public CubeMapper thisCubemapper;			//Cubemapper reference
	public string[] cubemapKeywords;			//Shader keywords to set the cubemap
	
	bool isCubemapSet					= false;
	
	
	void Update() {
		if (!isCubemapSet) {
			SetCubemap();
			isCubemapSet = true;
		}
	}
	
	void SetCubemap() {
		//Loops the materials and sets the cubemap
		Material[] materials = GetComponent<Renderer>().materials;
		
		foreach(Material thisMaterial in materials) {
			foreach(string thisKeyword in cubemapKeywords) {
				if (thisMaterial.HasProperty(thisKeyword))
					thisMaterial.SetTexture(thisKeyword, thisCubemapper.GetRenderTexture());
			}
		}
	}
	
}